test/Api/*       		usr/share/php/Raiffeisenbank/Test/PremiumAPI
test/Model/*    		usr/share/php/Raiffeisenbank/Test/Model
examples/example.env            var/lib/composer/php-vitexsoftware-rbczpremiumapi-dev/

debian/test/phpunit.xml         usr/share/php/Raiffeisenbank/Test

debian/test/composer.json    	usr/lib/php-vitexsoftware-rbczpremiumapi-dev
debian/test/bootstrap.php	usr/share/php/Raiffeisenbank/Test

examples/*      		usr/share/doc/php-vitexsoftware-rbczpremiumapi-dev
