<?php

/**
 * GetTransactionListApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  VitexSoftware\Raiffeisenbank
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 *
 * The version of the OpenAPI document: 1.1.20230222
 * Contact: info@vitexsoftware.cz
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace VitexSoftware\Raiffeisenbank\Test\Api;

use \PHPUnit\Framework\TestCase,
    \VitexSoftware\Raiffeisenbank\ApiClient,
    \VitexSoftware\Raiffeisenbank\PremiumAPI\GetTransactionListApi;

/**
 * GetTransactionListApiTest Class Doc Comment
 *
 * @category Class
 * @package  VitexSoftware\Raiffeisenbank
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GetTransactionListApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
        
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = new GetTransactionListApi(new ApiClient(['mocking' => true]));
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
        
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
        
    }

    /**
     * Test case for getTransactionList
     *
     * .
     *
     */
    public function testGetTransactionList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
